### ISSUE TITLE
Statistikk

### ISSUE THREAD

**Issue by starseekr** [scriptotek/bibrex#6]
Teller Bibrex antall utlån på et eksemplar/en ting? Kan være nyttig å se hvor mye et Arduino-kit brukes feks, som argumentasjon for innkjøp av flere eller lignende.

**Comment by danmichaelo** [comment]
Ja, det telles, men er vel foreløpig ikke eksponert i grensesnittet. Det kan fort fikses

**Comment by danmichaelo** [comment]
Siden februar har det ligget litt statistikk nederst på Ting-sidene:

![Skjermbilde 2019-07-14 kl  19 37 56](https://user-images.githubusercontent.com/434495/61187181-e7f95000-a66e-11e9-8aa8-98121fe64ccb.png)

Så lukker denne.
